[versions]
agp = "9.0.1"
dotenvJava = "3.2.0"
gson = "2.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.4"
constraintlayout = "2.2.1"
fragment = "1.8.9"
playServicesMaps = "20.0.0"
recyclerview = "1.4.0"
cardview = "1.0.0"
retrofit = "3.0.0"
browser = "1.9.0"
shimmer = "0.5.0"
okhttp = "5.3.2"
benMaves = "0.53.0"
playServicesAuth = "21.5.1"
biometricAuth = "1.1.0"

[libraries]
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
dotenv-java = { module = "io.github.cdimascio:dotenv-java", version.ref = "dotenvJava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometricAuth" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "benMaves"}